# Generated by Django 5.0.6 on 2026-08-22 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('kc_initial', models.FloatField(default=0.5, help_text='Phase germination/levee')),
                ('kc_developpement', models.FloatField(default=0.7, help_text='Croissance vegetative')),
                ('kc_mi_saison', models.FloatField(default=1.1, help_text='Floraison / mi-saison')),
                ('kc_maturation', models.FloatField(default=0.8, help_text='Maturation')),
                ('duree_phase_initiale_jours', models.IntegerField(default=20)),
                ('duree_phase_developpement_jours', models.IntegerField(default=25)),
                ('duree_phase_mi_saison_jours', models.IntegerField(default=35)),
                ('duree_phase_maturation_jours', models.IntegerField(default=20)),
                ('seuil_humidite_min_pct', models.FloatField(default=40.0, help_text="En dessous de ce %, on envisage d'irriguer")),
                ('seuil_humidite_max_pct', models.FloatField(default=70.0, help_text="Au dessus, le sol est considere gorge d'eau")),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='Ex: ESP32-001', max_length=50, unique=True)),
                ('mode_connexion', models.CharField(choices=[('mqtt', 'Connecte via MQTT (Wifi/cloud)'), ('ap_local', 'Mode Access Point local (secours, pas de reseau)'), ('hors_ligne', 'Hors ligne / injoignable')], default='hors_ligne', max_length=20)),
                ('derniere_communication', models.DateTimeField(blank=True, null=True)),
                ('niveau_batterie_pct', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('localite', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('agriculteur', 'Agriculteur'), ('agronome', 'Agronome'), ('technicien', 'Technicien'), ('admin', 'Administrateur'), ('demo', 'Compte demo (jury)')], default='agriculteur', max_length=20)),
                ('session_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_capteur', models.CharField(choices=[('humidite_temperature', 'Humidite + temperature (SEN0600)'), ('spectral_phenologique', 'Spectral - phase phenologique (AS7265x)')], max_length=30)),
                ('derniere_humidite_pct', models.FloatField(blank=True, null=True)),
                ('derniere_temperature_c', models.FloatField(blank=True, null=True)),
                ('derniere_lecture', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='LectureCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidite_pct', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.capteur')),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('localisation', models.CharField(help_text='Nom de la localite, ex: Aneho, Tsevie', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='core.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeRattachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parcelle_indique', models.CharField(help_text="Nom/localite indiques par l'agriculteur", max_length=200)),
                ('localisation_indiquee', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('refusee', 'Refusee')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('parcelle_liee', models.ForeignKey(blank=True, help_text="Rempli par l'agronome au moment de la validation", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parcelle')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='core.utilisateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Zone 1, Jardin, Potager...', max_length=80)),
                ('code_terrain', models.CharField(help_text='Code court utilise par le firmware ESP32 pour identifier cette zone dans les messages MQTT (ex: Z1, Z2, Z3). DOIT correspondre exactement au code defini dans le firmware -- voir firmware/smartwater_esp32/smartwater_esp32.ino', max_length=10, unique=True)),
                ('superficie_m2', models.FloatField(blank=True, null=True)),
                ('date_semis', models.DateField(help_text='Sert a calculer automatiquement la phase phenologique')),
                ('phase_source', models.CharField(choices=[('date_semis', 'Calculee via date de semis'), ('capteur_spectral', 'Detectee par capteur AS7265x')], default='date_semis', max_length=20)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='core.culture')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='Vanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermee')], default='fermee', max_length=10)),
                ('debit_theorique_l_min', models.FloatField(default=15.0, help_text="Debit theorique de l'electrovanne Hunter PGV 1po en litres/minute -- A VERIFIER sur la fiche technique du fabricant, cette valeur est une estimation.")),
                ('derniere_ouverture', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vannes', to='core.device')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vanne', to='core.zone')),
            ],
        ),
        migrations.CreateModel(
            name='RapportEconomieEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('volume_utilise_estime_l', models.FloatField()),
                ('volume_reference_manuel_l', models.FloatField(help_text="Estimation de ce qu'un arrosage manuel classique aurait consomme")),
                ('pourcentage_economise', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_eau', to='core.zone')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.zone'),
        ),
        migrations.CreateModel(
            name='DecisionIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('humidite_mesuree_pct', models.FloatField(blank=True, null=True)),
                ('pluie_prevue_mm', models.FloatField(blank=True, null=True)),
                ('etc_calcule_mm', models.FloatField(blank=True, help_text='Besoin en eau calcule (Kc x ETo)', null=True)),
                ('volume_irrigue_estime_l', models.FloatField(blank=True, null=True)),
                ('duree_minutes', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('aucune', "Pas d'irrigation - humidite suffisante"), ('reportee', 'Irrigation reportee - pluie prevue suffisante'), ('irrigation', 'Irrigation declenchee'), ('irrigation_manuelle', 'Irrigation demarree manuellement')], max_length=25)),
                ('explication', models.TextField(blank=True, help_text="Texte lisible affiche a l'agriculteur")),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.zone')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AddField(
            model_name='capteur',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='core.zone'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('sol_sec', 'Sol trop sec'), ('panne_capteur', 'Panne capteur'), ('batterie_faible', 'Batterie solaire faible'), ('vanne_anomalie', 'Anomalie sur une vanne')], max_length=20)),
                ('message', models.TextField()),
                ('canal', models.CharField(choices=[('push', 'Notification push'), ('sms', 'SMS'), ('ussd', 'USSD')], default='push', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('envoyee', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.device')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.zone')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
