# Generated by Django 5.0.6 on 2026-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='statut_maintenance',
            field=models.BooleanField(default=False, help_text='Coche manuellement si ce capteur est en cours de nettoyage/reparation.'),
        ),
    ]
