# Generated by Django 5.0.6 on 2026-08-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_capteur_statut_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionirrigation',
            name='decision',
            field=models.CharField(choices=[('aucune', "Pas d'irrigation - humidite suffisante"), ('reportee', 'Irrigation reportee - pluie prevue suffisante'), ('irrigation', 'Irrigation declenchee'), ('irrigation_manuelle', 'Irrigation demarree manuellement'), ('irrigation_automatique', 'Irrigation demarree automatiquement (delai 1h depasse)')], max_length=25),
        ),
    ]
