# Generated by Django 5.0.6 on 2026-08-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parcelle_meteo_cache_14j_parcelle_meteo_cache_24h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='meteo_cache_14j',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='meteo_cache_24h',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='meteo_cache_maj_le',
        ),
    ]
