# Generated by Django 5.0.6 on 2026-08-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_parcelle_meteo_cache_14j_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='meteo_cache_14j',
            field=models.JSONField(blank=True, help_text='Cache des previsions 14 jours, rafraichi periodiquement', null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='meteo_cache_24h',
            field=models.JSONField(blank=True, help_text='Cache des previsions heure par heure (24h), rafraichi periodiquement', null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='meteo_cache_maj_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
