# Generated by Django 5.0.6 on 2026-08-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parcelle_meteo_cache_14j_parcelle_meteo_cache_24h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanne',
            name='fermeture_prevue',
            field=models.DateTimeField(blank=True, help_text='Calculee automatiquement : ouverture + duree', null=True),
        ),
    ]
