# Generated by Django 5.0.6 on 2026-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vanne_fermeture_prevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='dernier_azote_ppm',
            field=models.FloatField(blank=True, help_text='Azote (N)', null=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='dernier_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='dernier_phosphore_ppm',
            field=models.FloatField(blank=True, help_text='Phosphore (P)', null=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='dernier_potassium_ppm',
            field=models.FloatField(blank=True, help_text='Potassium (K)', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='ph_max',
            field=models.FloatField(blank=True, help_text='pH maximum acceptable pour cette culture', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='ph_min',
            field=models.FloatField(blank=True, help_text='pH minimum acceptable pour cette culture', null=True),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='type_capteur',
            field=models.CharField(choices=[('humidite_temperature', 'Humidite + temperature (+ pH/NPK si disponible)'), ('spectral_phenologique', 'Spectral - phase phenologique (AS7265x)')], max_length=30),
        ),
    ]
