# Generated by Django 5.0.6 on 2026-08-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_capteur_dernier_azote_ppm_capteur_dernier_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='dernier_ndvi',
            field=models.FloatField(blank=True, help_text='Indice de vegetation calcule (capteur spectral)', null=True),
        ),
        migrations.AddField(
            model_name='lecturecapteur',
            name='ndvi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='mode_calcul_phase',
            field=models.CharField(choices=[('date_semis', 'Date de semis'), ('capteur', 'Capteur phenologique (NDVI)')], default='date_semis', max_length=15),
        ),
    ]
